/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface GenerateAnchorReq {
  secrets: Array<SecretDto>
}

export interface GenerateAnchorRes {
  anchor: Array<string>
}

export interface GeneratePoseidonHashReq {
  inputs: Array<string>
}

export interface GeneratePoseidonHashRes {
  hash: string
}

export interface GenerateProofReq {
  pkPath: string
  jwts: Array<string>
  pkOps: Array<string>
  /** 예: merkle path를 레벨별 string 배열로 표현한다면 Vec<Vec<String>> */
  merklePaths: Array<Array<string>>
  /** JS number는 안전정수 범위가 있으니 보통 u32/u64 권장 */
  leafIndices: Array<number>
  root: string
  anchor: Array<string>
  hSignUserOp: string
  counter: string
  random: string
}

export interface GenerateProofRes {
  proofs: Array<Array<string>>
  sharedInputs: Array<string>
  partialRhsList: Array<string>
}

export interface GetZkParameters {
  maxJwtB64Len: number
  maxPayloadB64Len: number
  maxAudLen: number
  maxExpLen: number
  maxIssLen: number
  maxNonceLen: number
  maxSubLen: number
  n: number
  k: number
  treeHeight: number
  claims: Array<string>
}

export declare function napiGenerateAnchor(req: GenerateAnchorReq): GenerateAnchorRes

export declare function napiGeneratePoseidonHash(req: GeneratePoseidonHashReq): GeneratePoseidonHashRes

export declare function napiGenerateSeparatedProof(req: GenerateProofReq): GenerateProofRes

export declare function napiGetZkParameters(): GetZkParameters

export interface ProofBundle {
  proof: Array<string>
  publicInputs: Array<string>
}

export interface SecretDto {
  aud?: string
  iss: string
  sub: string
}
